name       : mate-user-guide
version    : 1.22.0
release    : 7
source     :
    - https://github.com/mate-desktop//mate-user-guide/archive/v1.22.0.tar.gz : ff552e20e1a939d70be47f6a16ae0d853415d3ed756f96d2258270e217c42437
license    : GFDL-1.1-or-later
component  : desktop.mate
summary    : This package contains documents which will be packaged together and shipped as mate-user-guide in the core MATE distribution.
description: |
    This package contains documents which will be packaged together and shipped as mate-user-guide in the core MATE distribution.  They should be documents targeted for end-users of MATE and have general MATE applicability.
builddeps  :
    - itstool
    - mate-common
    - yelp-tools
rundeps    :
    - yelp
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
