name       : mate-user-guide
version    : 1.26.0
release    : 12
source     :
    - https://github.com/mate-desktop/mate-user-guide/releases/download/v1.26.0/mate-user-guide-1.26.0.tar.xz : 0581d45053e9a1c16925c3154341b5b21140905a22b1bd3caa84619f9f05c2c0
license    : GFDL-1.1-or-later
component  : desktop.mate
summary    : This package contains documents which will be packaged together and shipped as mate-user-guide in the core MATE distribution.
description: |
    This package contains documents which will be packaged together and shipped as mate-user-guide in the core MATE distribution.  They should be documents targeted for end-users of MATE and have general MATE applicability.
builddeps  :
    - itstool
rundeps    :
    - yelp
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
