name       : mate-user-guide
version    : 1.27.0
release    : 13
source     :
    - https://github.com/mate-desktop/mate-user-guide/releases/download/v1.27.0/mate-user-guide-1.27.0.tar.xz : b1a1f995341a386a4a6913b66c3262e9303cce42f9529a7f7c80b8940f5b229f
license    : GFDL-1.1-or-later
component  : desktop.mate
summary    : This package contains documents which will be packaged together and shipped as mate-user-guide in the core MATE distribution.
description: |
    This package contains documents which will be packaged together and shipped as mate-user-guide in the core MATE distribution.  They should be documents targeted for end-users of MATE and have general MATE applicability.
builddeps  :
    - itstool
rundeps    :
    - yelp
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
