name       : mate-user-guide
version    : 1.20.0
release    : 2
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-user-guide-1.20.0.tar.xz : 82835c4f4fd72d1dd70c4469ee0307e78ccf8dd813a756e5de67a25ffda639d8
license    : GFDL-1.1
component  : desktop.mate
summary    : This package contains documents which will be packaged together and shipped as mate-user-guide in the core MATE distribution.
description: |
    This package contains documents which will be packaged together and shipped as mate-user-guide in the core MATE distribution.  They should be documents targeted for end-users of MATE and have general MATE applicability.
builddeps  :
    - itstool
rundeps    :
    - yelp
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
