name       : mate-user-guide
version    : 1.22.2
release    : 9
source     :
    - https://github.com/mate-desktop/mate-user-guide/archive/v1.22.2.tar.gz : 6c5147c4fd2f0e0590c86947e22d1707fbd3a70b4b8eb0d41ab1aea6d12da78c
license    : GFDL-1.1-or-later
component  : desktop.mate
summary    : This package contains documents which will be packaged together and shipped as mate-user-guide in the core MATE distribution.
description: |
    This package contains documents which will be packaged together and shipped as mate-user-guide in the core MATE distribution.  They should be documents targeted for end-users of MATE and have general MATE applicability.
builddeps  :
    - itstool
    - mate-common
    - yelp-tools
rundeps    :
    - yelp
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
