name       : mate-user-guide
version    : 1.22.1
release    : 8
source     :
    - https://github.com/mate-desktop/mate-user-guide/archive/v1.22.1.tar.gz : 4d94061184cf07970b1b1c0bf957f80401fa8d4f67edf898ead1c5a0af871455
license    : GFDL-1.1-or-later
component  : desktop.mate
summary    : This package contains documents which will be packaged together and shipped as mate-user-guide in the core MATE distribution.
description: |
    This package contains documents which will be packaged together and shipped as mate-user-guide in the core MATE distribution.  They should be documents targeted for end-users of MATE and have general MATE applicability.
builddeps  :
    - itstool
    - mate-common
    - yelp-tools
rundeps    :
    - yelp
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
